name: Quality Checks

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-check:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  check-todos:
    name: Check TODOs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for TODO comments
        run: |
          if grep -r "TODO\|FIXME\|XXX" src/ ; then
            echo "Found TODO/FIXME/XXX comments. Please resolve before merging."
            exit 1
          fi
        continue-on-error: true

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            **/*.md
            **/*.ts
          config: .cspell.json
        continue-on-error: true
