name: Release Drafter Autolabeler

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  pull_request_target:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  autolabel_pr:
    name: Autolabel PR
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository)
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Autolabel PR
        uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
